### ISSUE TITLE
Representing graphs in other formats

### ISSUE THREAD

**Issue by PaulKinlan** [breadboard-ai/breadboard#219]
When I started with breadboard I used to edit graphs directly. It helped me to get started and I imagine pure configuration methods will help a lot of other people too, because at least for me I could conceptualise the graph easily. 

After a while it got quite verbose and very easy to make mistakes. Recently, I've been wondering if there might be other ways to represent the graph in a way that is easy for people to author (note: I don't believe we should change the file format save for thinking about #218)

I was idly noodling on a YAML to JSON converter and it seems pretty simple to have the graph represented in a YAML. The following would be trivial to convert

```YAML
edges:
  - from: input
    out: url
    to: fetch
    in: url
  - from: fetch
    out: response
    to: output
    in: text

nodes: # Testing the different ways to express objects.
  - { id: input, type: input }
  - { id: fetch, type: fetch, configution: { raw: true} }
  - id: output
    type: output

kits: 
  -  url: "npm:@google-labs/core-kit"
```

While the above would directly convert to JSON and it is more compact, it's not by much.

As per #218, I think we can get a lot more efficient with the representation of the edges

```
edges:
  - input.url->fetch.url
  - fetch.response->output.text

nodes: # Testing the different ways to express objects.
  - { id: input, type: input }
  - { id: fetch, type: fetch, configution: { raw: true} }
  - id: output
    type: output

kits: 
  -  url: "npm:@google-labs/core-kit"
```
